---
# tasks file for sa-vpn-pptp-client

   - name: PPP Client | install dependencies
     apt: package="{{item}}" state="present"
     with_items:
       - "pptp-linux"


   - name: PPP Client | Configure chap secrets /etc/ppp/chap-secrets
     template: src="{{role_dir}}/templates/chap-secrets.j2" dest="/etc/ppp/chap-secrets"
     become: yes
     tags:
       - ppp-client

   - name: PPP Client | Configure profile /etc/ppp/peers/VPNprofile
     template: src="{{role_dir}}/templates/vpnprofile.j2" dest="/etc/ppp/peers/{{pptp_profile}}"
     become: yes
     tags:
       - ppp-client

   - name: PPP Client | Configure tunnel in /etc/network/interfaces
     blockinfile:
        dest: /etc/network/interfaces
        block: |
          auto tunnel
          iface tunnel inet ppp
              provider {{pptp_profile}}
     become: yes
     tags:
       - ppp-client


   - name: PPP Client | Configure /etc/ppp/ip-up.d/VPNprofile
     template: src="{{role_dir}}/templates/profile_up.j2" dest="/etc/ppp/ip-up.d/{{pptp_profile}}" mode="u=rwx,g=rx,o=rx"
     become: yes
     tags:
       - ppp-client

   - name: PPP Client | Configure /etc/ppp/ip-down.d/VPNprofile
     template: src="{{role_dir}}/templates/profile_down.j2" dest="/etc/ppp/ip-down.d/{{pptp_profile}}" mode="u=rwx,g=rx,o=rx"
     become: yes
     tags:
       - ppp-client


   - name: PPP Client | Restart networking
     service: name="networking" state="restarted"
     become: yes
     when: docker_test is not defined
     tags:
       - ppp-client
